[package]
name = "rengin"
version = "0.1.0"
authors = ["Ilia <ilia.shibaev@gmail.com>"]
edition = "2021"

[workspace]
members = ["run-wasm"]

[features]
default = ["native"]
native = ["glam/std"]
webgl = ["glam/libm"]

[dependencies]
glam = { version = "0.27", default-features = false, features = ["bytemuck"] }
winit = "0.29"
tobj = "4.0"
bincode = "1.3.3"
env_logger = "0.11"
log = "0.4"
bytemuck = { version = "1.14", features = ["derive"] }
rand = "0.8.5"
yaml-rust = "0.4"
linked-hash-map = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
image = "0.25"
itertools = "0.13"
clap = { version = "4.5", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = { version = "0.3" }
wgpu = { version = "0.20", features = ["vulkan-portability"] }
# wgpu = { git = "https://github.com/gfx-rs/wgpu.git", branch = "trunk", package = "wgpu", features= ["vulkan-portability"] }
# ash =  { version="0.37", default-features = false, features = ["linked", "debug"] }
# ash-window = "0.10"
#renderdoc = "0.10.1"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-rs-async-executor = "0.9.0"
# wgpu_gecko = { git = "https://github.com/gfx-rs/wgpu.git", branch = "gecko", package = "wgpu" }
# console_error_panic_hook = "0.1.6"
# console_log = "0.1.2"
# wasm-bindgen-futures = "0.4.23"
# wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
# instant = { version = "0.1", features = [ "stdweb" ] }
# getrandom = { version = "0.2", features = ["js"] }

[profile.release]
debug = true
