[package]
name = "rengin"
version = "0.1.0"
authors = ["Ilia <ilia.shibaev@gmail.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]

std = ["glam/std"]
libm = ["glam/libm"]

[dependencies]
glam = { version = "0.20.1", default-features = false, features = ["bytemuck"] }
winit = "0.25.0"
wgpu = {version = "0.11"}
tobj = "3.1.0"
futures = { version = "0.3.15"}
bincode = "1.3.3"
env_logger = "0.8"
log = "0.4"
bytemuck = { version = "1.7.2", features = [ "derive" ] }
#renderdoc = "0.10.1"

[profile.release] 
debug = true