[package]
name = "rengin"
version = "0.1.0"
authors = ["Ilia <ilia.shibaev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]

std = ["glam/std"]
libm = ["glam/libm"]

[dependencies]
glam = { version = "0.17.1", default-features = false, features = ["serde"] }
winit = "0.25.0"
#wgpu = {version = "0.9",features=["vulkan-portability"]}
wgpu = "0.9"
image = "0.23"
tobj = "3.0.1"
futures = { version = "0.3.15"}
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[profile.release] 
debug = true